"""empty message

Revision ID: b5dcc5de9149
Revises: 
Create Date: 2020-06-09 08:41:17.733215

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b5dcc5de9149'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('order_items', 'total_price',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('order_items', 'price')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_items', sa.Column('price', sa.INTEGER(), nullable=False))
    op.alter_column('order_items', 'total_price',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
